version: '3.9'

services:
  app:
    container_name: currency
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - '8080:8080'
    restart: on-failure
    image: 'currency'